//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatatableCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        [Required(ErrorMessage = "First name is required !!!")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last name is required !!!")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Email is required !!!")]
        public string Email { get; set; }
        [Required(ErrorMessage = "City is required !!!")]
        public string City { get; set; }
        [Required(ErrorMessage = "Country is required !!!")]
        public string Country { get; set; }
    }
}
